import {
  aktueltPage,
  calendarEntry,
  calendarSection,
  footer,
  header,
  homePage,
  kontaktPage,
  omOssPage,
  omOssPerson,
  sectionAnnet,
  sectionKalender,
  sectionKjope,
  sectionKontakt,
  sectionOmOss,
} from './homePage.js'

export const schemaTypes = [
  homePage,
  aktueltPage,
  omOssPage,
  kontaktPage,
  calendarSection,
  header,
  footer,
  omOssPerson,
  sectionKalender,
  sectionAnnet,
  sectionKjope,
  sectionKontakt,
  sectionOmOss,
  calendarEntry,
]
